version: '3.8'

services:
  # Redis service
  redis:
    image: redis:7-alpine
    container_name: rampagent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # RampAgent API service
  api:
    build: .
    container_name: rampagent-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data:/app/data:ro  # Mount data folder as read-only
      - ./logs:/app/logs      # Mount logs folder
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
