version: '3.8'

services:
  # Redis service
  redis:
    image: redis:7-alpine
    container_name: rampagent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # RampAgent API service
  api:
    build: .
    container_name: rampagent-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONFIG_REPO_URL=https://github.com/vaccfr/RampAgent-Config.git
      - CONFIG_BRANCH=main
      - GH_SECRET=${GH_SECRET:-}
    volumes:
      - rampagent-config:/app/data 
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/airports"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
    driver: local
  rampagent-config:
    driver: local
