name: Container Image CI

on:
  push:
    branches:
      - "Dev"
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            docker build --pull \
              -t ${{ env.REGISTRY }}/alexisbalzano/rampagent_api:${TAG_NAME} .
            docker push ${{ env.REGISTRY }}/alexisbalzano/rampagent_api:${TAG_NAME}
          else
            docker build --pull \
              -t ${{ env.REGISTRY }}/alexisbalzano/rampagent_api:dev .
            docker push ${{ env.REGISTRY }}/alexisbalzano/rampagent_api:dev
          fi
